# config.yaml
data_root: ./data
chunk_size: 400
chunk_overlap: 100
top_k: 5
top_k_wiki: 3
default_thres: 0.0

# For ewha questions
ewha_thres: 0.001
ewha_faiss_path: ./db/ewha/ewha_faiss_fix
ewha_bm25_path: ./db/ewha/bm25_fix

summ_chroma_path: ./db/summ_chroma
summ_faiss_path: ./db/summ_faiss

pc_chroma_path: ./db/pc_chroma_new
pc_faiss_path: ./db/pc_faiss
pc_chroma_cos_path: ./db/pc_chroma_cos

raptor_faiss_path: ./db/raptor/RAPTOR_faiss_fix

# For mmlu questions
mmlu_thres: 0.4
business_faiss_path: ./db/raptor/business
law_faiss_path: ./db/raptor/law
psychology_faiss_path: ./db/raptor/psychology
philosophy_faiss_path: ./db/raptor/philosophy
history_faiss_path: ./db/raptor/history